input UpdateActorInput {
  actorId: String!
  data: ActorInput
}

# Nested inputs
input ActorInput {
  firstName: String
  lastName: String
  email: String
  password: String
  phoneCountryCode: String
  phone: String
  address1: String
  address2: String
  city: String
  state: String
  postalCode: String
}
