type OpenAuth {
  id: ID!
  actor: Actor!
  provider: ProviderName!
  accessToken: String!
  refreshToken: String
  expiresAt: String!
  updatedAt: String!
  createdAt: String!
  deletedAt: String
}

type BlacklistedToken {
  id: ID!
  token: String!
  updatedAt: String!
  createdAt: String!
  deletedAt: String
}

# Enums
enum ProviderName {
  GOOGLE
}
