extend type Query {
  getActorSecurityQuestionAnswers(
    input: GetActorSecurityQuestionAnswerInput!
  ): [SecurityQuestionAnswer!]!
  validateAccess: TokenPayload!
}

extend type Mutation {
  registerActor(input: RegisterActorInput!): TokenPayload!
  confirmActor(input: ConfirmActorInput!): ActorPayload!
  loginActor(input: LoginActorInput!): TokenPayload!
  setActorSecurityQuestionAnswers(
    input: ActorSecurityQuestionAnswerInput!
  ): ActorPayload!
  verifyActorSecurityQuestionAnswers(
    input: ActorSecurityQuestionAnswerInput!
  ): ActorPayload!
  resetPassword(input: ResetPasswordInput!): ActorPayload!
  changePassword(input: ChangePasswordInput!): ActorPayload!
  unlockAccount(input: UnlockAccountInput!): ActorPayload!
  sendAuthEmail(input: SendAuthEmail!): ActorPayload!
  logoutActor(input: LogoutActorInput!): String
}
