extend type Query {
  getUserSecurityQuestionAnswers(
    input: UserSecurityQuestionAnswerInput!
  ): [SecurityQuestionAnswer!]!
  validateAccess: TokenPayload!
}

extend type Mutation {
  registerActor(input: RegisterActorInput!): TokenPayload!
  confirmActor(input: ConfirmActorInput!): ActorPayload!
  loginUser(input: LoginUserInput!): TokenPayload!
  setUserSecurityQuestionAnswers(input: UserSecurityQuestionInput!): String
  verifyUserSecurityQuestionAnswers(input: UserSecurityQuestionInput!): String
  resetPassword(input: ResetPasswordInput!): String
  changePassword(input: ChangePasswordInput!): String
  unlockAccount(input: UnlockAccountInput!): String
  sendAuthEmail(input: SendAuthEmail!): String
  logoutUser(input: LogoutUserInput!): String
}
