input RegisterActorInput {
  firstName: String!
  lastName: String!
  email: String!
  password: String!
}

input ConfirmActorInput {
  code: Int!
}

input LoginActorInput {
  email: String!
  password: String!
  rememberMe: Boolean!
}

input ActorSecurityQuestionAnswerInput {
  actorId: String!
  answers: [SecurityQuestionAnswerInput!]!
}

input GetActorSecurityQuestionAnswerInput {
  actorId: String!
}

input ResetPasswordInput {
  email: String!
}

input ChangePasswordInput {
  code: Int!
  password: String!
}

input UnlockAccountInput {
  code: Int!
}

input SendAuthEmailInput {
  email: String!
  type: EmailType!
}

input LogoutActorInput {
  token: String!
}

# Nested inputs
input SecurityQuestionAnswerInput {
  shortName: String!
  answer: String!
}

# Enums
enum EmailType {
  CONFIRMATION_EMAIL
  UNLOCK_ACCOUNT_EMAIL
}
