type SecurityQuestion {
  id: ID!
  shortName: String!
  question: String!
  updatedAt: String!
  createdAt: String!
  deletedAt: String
}

type SecurityQuestionAnswer {
  id: ID!
  actorAccount: ActorAccount!
  actorSecurityQuestion: SecurityQuestion!
  answer: String!
  updatedAt: String!
  createdAt: String!
  deletedAt: String
}
